# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

target 'ShareMe' do
# Uncomment this line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

# Pods for SocialNetwork
pod 'THCalendarDatePicker', '~> 1.2'
pod 'JSONModel'
pod 'DLRadioButton', '~> 1.4'
end
